# Вариации запровов к серверу:

# GET https://13.ecmascript.pages.academy/big-trip/points HTTP/1.1
# Authorization: Basic NS43cqsibarQ5EJ
# Content-Type: application/json

# GET https://13.ecmascript.pages.academy/big-trip/offers HTTP/1.1
# Authorization: Basic NS43cqsibarQ5EJ
# Content-Type: application/json

GET https://13.ecmascript.pages.academy/big-trip/destinations HTTP/1.1
Authorization: Basic NS43cqsibarQ5EJ
Content-Type: application/json

# Существует отличная альтернатива - расширение для браузера rested
